export const PaintActions = {
    UPDATE_CANVAS: "UPDATE_CANVAS",
    UPDATE_CTX: "UPDATE_CTX",
    UPDATE_SIZE: "UPDATE_SIZE",
    UPDATE_COLOR: "UPDATE_COLOR",
    UPDATE_TEXT_AREA: "UPDATE_TEXT_AREA"
}